<?php
/**
 * MASCOTIENDAS - Descargador de imágenes
 * ----------------------------------------
 * Sube este archivo a la raíz de tu proyecto en SiteGround.
 * Ábrelo UNA VEZ desde el navegador: https://tudominio.cl/descargar_imagenes.php
 * ¡ELIMÍNALO del servidor cuando termine!
 *
 * Qué hace:
 *  1. Crea la carpeta /uploads/productos/ en tu servidor
 *  2. Descarga las 236 imágenes desde mascotiendas.cl
 *  3. Actualiza las URLs en tu base de datos
 */

// ─── CONFIGURA TU BD ───────────────────────────
define('DB_HOST', '34.174.176.130');
define('DB_NAME', 'db3lgldhuiu1al');   // <-- cambia esto
define('DB_USER', 'uctn6jogdfw2i');          // <-- cambia esto
define('DB_PASS', '{#2L41b1G3y:');         // <-- cambia esto
// ────────────────────────────────────────────────

// Carpeta donde se guardarán las imágenes (relativa a este archivo)
define('IMG_DIR',  __DIR__ . '/uploads/productos/');
define('IMG_URL',  '/uploads/productos/');   // URL pública relativa

set_time_limit(300); // 5 minutos, suficiente para 236 imágenes
ini_set('display_errors', 1);

// Crear carpeta si no existe
if (!is_dir(IMG_DIR)) {
    mkdir(IMG_DIR, 0755, true);
    echo "<p>✅ Carpeta <code>uploads/productos/</code> creada.</p>";
} else {
    echo "<p>📁 Carpeta ya existe.</p>";
}

// Conectar a BD
try {
    $pdo = new PDO("mysql:host=".DB_HOST.";dbname=".DB_NAME.";charset=utf8mb4", DB_USER, DB_PASS);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "<p>✅ Conexión a BD exitosa.</p>";
} catch (PDOException $e) {
    die("<p>❌ Error BD: " . $e->getMessage() . "</p>");
}

// Lista de imágenes (generada automáticamente desde tu CSV)
$imagenes = [
  ['producto_id'=>1, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/dockennedy-adulto-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'dockennedy-adulto-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>2, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/dockennedy-adulto-control-de-peso-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'dockennedy-adulto-control-de-peso-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>3, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/dockennedy-breeder-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'dockennedy-breeder-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>4, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/dockennedy-cachorro-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'dockennedy-cachorro-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>5, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/dockennedy-joint-care-todas-las-edades-razas-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'dockennedy-joint-care-todas-las-edades-razas-15-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>6, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/fit-formula-adulto-raza-pequena-10-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'fit-formula-adulto-raza-pequena-10-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>7, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/fit-formula-adulto-todas-las-razas-20-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'fit-formula-adulto-todas-las-razas-20-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>8, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/fit-formula-cachorro-todas-las-razas-20-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'fit-formula-cachorro-todas-las-razas-20-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>9, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/fit-formula-senior-raza-mediana-grande-20-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'fit-formula-senior-raza-mediana-grande-20-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>10, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/fit-formula-senior-raza-pequena-chica-10-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'fit-formula-senior-raza-pequena-chica-10-kg-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>11, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/nomade-adulto-20-kg-raza-pequena-chica-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'nomade-adulto-20-kg-raza-pequena-chica-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>12, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/nomade-adulto-20-kg-raza-grande-mediana-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'nomade-adulto-20-kg-raza-grande-mediana-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>13, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-adulto-raza-pequena-chica-mini-2-kg-salmon-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'sense-adulto-raza-pequena-chica-mini-2-kg-salmon-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>14, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-adulto-todas-las-razas-12-kg-pollo-pato-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'sense-adulto-todas-las-razas-12-kg-pollo-pato-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>15, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-adulto-raza-todas-las-razas-12-kg-pato-pavo-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'sense-adulto-raza-todas-las-razas-12-kg-pato-pavo-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>16, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-adulto-todas-las-razas-12-kg-salmon-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'sense-adulto-todas-las-razas-12-kg-salmon-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>17, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-cachorro-todas-las-razas-12-kg-pavo-salmon-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'sense-cachorro-todas-las-razas-12-kg-pavo-salmon-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>18, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/fit-formula-gatos-adultos-10-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'fit-formula-gatos-adultos-10-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>19, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/nomade-gatos-adultos-10-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'nomade-gatos-adultos-10-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>20, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-esterilizado-7-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-esterilizado-7-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>20, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-esterilizado-7-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-esterilizado-7-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>21, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-esterilizado-7-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-esterilizado-7-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>21, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-esterilizado-7-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-esterilizado-7-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>22, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-urinary-problemas-urinarios-3-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-urinary-problemas-urinarios-3-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>22, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-urinary-problemas-urinarios-3-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-urinary-problemas-urinarios-3-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>23, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-urinary-problemas-urinarios-3-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-urinary-problemas-urinarios-3-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>23, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-urinary-problemas-urinarios-3-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-urinary-problemas-urinarios-3-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>24, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-kitten-gatitto-3-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-kitten-gatitto-3-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>24, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-kitten-gatitto-3-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-kitten-gatitto-3-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>25, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-gatos-adulto-7-senior-3-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-gatos-adulto-7-senior-3-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>26, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-adultos-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-adultos-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>26, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-adultos-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-adultos-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>27, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-castrados-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-castrados-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>27, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-castrados-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-castrados-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>28, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-filhotes-gatitos-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-filhotes-gatitos-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>28, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-filhotes-gatitos-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-scaled.webp', 'filename'=>'biofresh-gatos-filhotes-gatitos-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-scaled.webp'],
  ['producto_id'=>29, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-adultos-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-adultos-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>29, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-adultos-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-adultos-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>30, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-castrados-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-castrados-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>30, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/biofresh-gatos-castrados-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp', 'filename'=>'biofresh-gatos-castrados-1-5-kg-1-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-1-scaled.webp'],
  ['producto_id'=>31, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/taste-of-the-wild-rockymountain-6-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'taste-of-the-wild-rockymountain-6-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>32, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/taste-of-the-wild-canyon-river-6-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'taste-of-the-wild-canyon-river-6-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>33, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-gatos-kitten-gatito-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'sense-gatos-kitten-gatito-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>34, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-gatos-kitten-gatito-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'sense-gatos-kitten-gatito-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>35, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-gatos-adulto-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'sense-gatos-adulto-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>36, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-gatos-adulto-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'sense-gatos-adulto-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>37, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-gatos-esterilizado-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'sense-gatos-esterilizado-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>38, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/sense-gatos-esterilizado-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'sense-gatos-esterilizado-6-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>39, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-adulos-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-adulos-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>40, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-adulos-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-adulos-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>41, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-kitten-gatito-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-kitten-gatito-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>42, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-kitten-gatito-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-kitten-gatito-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>43, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-urinary-problemas-urinarios-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-urinary-problemas-urinarios-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>44, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-urinary-problemas-urinarios-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-urinary-problemas-urinarios-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>45, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-control-peso-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-control-peso-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>46, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-control-peso-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-control-peso-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>47, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-2-5-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-comprimido.webp', 'filename'=>'simparica-2-5-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-comprimido.webp'],
  ['producto_id'=>48, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-2-5-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-comprimido.webp', 'filename'=>'simparica-2-5-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-comprimido.webp'],
  ['producto_id'=>49, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-5-10-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos.webp', 'filename'=>'simparica-5-10-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos.webp'],
  ['producto_id'=>50, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-5-10-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos.webp', 'filename'=>'simparica-5-10-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos.webp'],
  ['producto_id'=>51, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-10-20-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos-tienda-mascotas-farmacia.webp', 'filename'=>'simparica-10-20-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos-tienda-mascotas-farmacia.webp'],
  ['producto_id'=>52, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-10-20-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos-tienda-mascotas-farmacia.webp', 'filename'=>'simparica-10-20-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos-tienda-mascotas-farmacia.webp'],
  ['producto_id'=>53, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-20-40-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-3-comprimidos.webp', 'filename'=>'simparica-20-40-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-3-comprimidos.webp'],
  ['producto_id'=>54, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-40-60-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-comprimido.webp', 'filename'=>'simparica-40-60-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-comprimido.webp'],
  ['producto_id'=>55, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-40-60-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-3-comprimidos.webp', 'filename'=>'simparica-40-60-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-3-comprimidos.webp'],
  ['producto_id'=>56, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-trio-20-40-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos.webp', 'filename'=>'simparica-trio-20-40-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos.webp'],
  ['producto_id'=>57, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-trio-20-40-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos.webp', 'filename'=>'simparica-trio-20-40-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-1-3-comprimidos.webp'],
  ['producto_id'=>58, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/simparica-trio-40-60-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-3-comprimidos.webp', 'filename'=>'simparica-trio-40-60-kgs-antiparasitario-antipulgas-mascotiendas-la-serena-coquimbo-3-comprimidos.webp'],
  ['producto_id'=>59, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/criadores-perro-maintenance-high-pro-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'criadores-perro-maintenance-high-pro-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>60, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/maxine-perro-senior-21-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'maxine-perro-senior-21-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>61, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/monge-perro-vet-solution-dermatosis-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'monge-perro-vet-solution-dermatosis-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>62, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/monge-perro-adulto-raza-mediana-pollo-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'monge-perro-adulto-raza-mediana-pollo-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>65, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/proterline-adulto-22-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'proterline-adulto-22-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>66, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/criadores-perro-maintenance-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'criadores-perro-maintenance-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>67, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/monge-gato-adulto-ambientes-interiores-alto-pollo-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'monge-gato-adulto-ambientes-interiores-alto-pollo-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>68, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/maxine-perro-adulto-21-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'maxine-perro-adulto-21-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>69, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/maxine-perro-cachorro-21-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'maxine-perro-cachorro-21-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>70, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/natural-food-perro-cachorro-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'natural-food-perro-cachorro-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>71, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-adulto-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-adulto-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>71, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-adulto-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-adulto-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>72, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-adulto-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-adulto-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>72, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-adulto-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-adulto-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>73, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-cachorro-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-cachorro-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>73, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-cachorro-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-cachorro-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>74, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-cachorro-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-cachorro-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>74, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-cachorro-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-cachorro-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>75, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-senior-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-senior-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>75, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-senior-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-senior-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>76, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-senior-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-senior-pollo-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>76, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/poema-perro-senior-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'poema-perro-senior-salmon-arroz-3-15-kgs-mascotiendas-cl-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>77, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-perro-veterinary-dieta-gastroenteris-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'pro-plan-perro-veterinary-dieta-gastroenteris-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>78, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-perro-reducido-calorias-3-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'pro-plan-perro-reducido-calorias-3-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>79, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/pro-plan-perro-piel-estoago-sensible-3-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'pro-plan-perro-piel-estoago-sensible-3-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>80, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/agility-gato-urinary-problemas-urinarios-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'agility-gato-urinary-problemas-urinarios-10-1-5-kg-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>81, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/catshow-purina-gato-adulto-10-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.png', 'filename'=>'catshow-purina-gato-adulto-10-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.png'],
  ['producto_id'=>82, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/catshow-delimix-purina-gato-adulto-10-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.jpg', 'filename'=>'catshow-delimix-purina-gato-adulto-10-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.jpg'],
  ['producto_id'=>83, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/catshow-purina-gato-gatito-kitten-10-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.jpg', 'filename'=>'catshow-purina-gato-gatito-kitten-10-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.jpg'],
  ['producto_id'=>84, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/catpro-gatos-adultos-15-kgs-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-la-antena.png', 'filename'=>'catpro-gatos-adultos-15-kgs-mascotiendas-cl-comida-para-gatos-tienda-mascotas-la-serena-coquimbo-la-antena.png'],
  ['producto_id'=>85, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/monge-gato-adulto-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo-la-antena.jpg', 'filename'=>'monge-gato-adulto-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo-la-antena.jpg'],
  ['producto_id'=>86, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/monge-vet-solution-gato-dermatosis-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'monge-vet-solution-gato-dermatosis-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>87, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/monge-vet-solution-gato-renal-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.png', 'filename'=>'monge-vet-solution-gato-renal-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.png'],
  ['producto_id'=>88, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/07/monge-gato-senior-7-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'monge-gato-senior-7-1-5-kgs-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>89, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/purina-one-gato-esterilizado-6-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.jpg', 'filename'=>'purina-one-gato-esterilizado-6-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.jpg'],
  ['producto_id'=>90, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/purina-one-gato-adulto-6-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.jpg', 'filename'=>'purina-one-gato-adulto-6-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.jpg'],
  ['producto_id'=>91, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/purina-one-gato-gatitos-6-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.webp', 'filename'=>'purina-one-gato-gatitos-6-kgs-comida-gato-mascotiendas-la-serena-coquimbo-tienda-mascotas.webp'],
  ['producto_id'=>92, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/taste-of-the-wild-lowland-creek-pato-6-6-kg-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'taste-of-the-wild-lowland-creek-pato-6-6-kg-mascotiendas-cl-comida-gatos-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>93, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-cat-global-bentonita-8-5-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-cat-global-bentonita-8-5-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>94, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-cool-clean-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-cool-clean-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>95, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-fit-formula-cafe-moca-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'arena-gatos-fit-formula-cafe-moca-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>96, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-fit-formula-lavanda-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.png', 'filename'=>'arena-gatos-fit-formula-lavanda-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.png'],
  ['producto_id'=>97, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-baby-powder-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-kikki-kat-baby-powder-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>97, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-baby-powder-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-1.jpg', 'filename'=>'arena-gatos-kikki-kat-baby-powder-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-1.jpg'],
  ['producto_id'=>97, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-baby-powder-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-2.jpg', 'filename'=>'arena-gatos-kikki-kat-baby-powder-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-2.jpg'],
  ['producto_id'=>98, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-carbon-activo-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-kikki-kat-carbon-activo-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>98, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-carbon-activo-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-1.jpg', 'filename'=>'arena-gatos-kikki-kat-carbon-activo-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-1.jpg'],
  ['producto_id'=>98, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-carbon-activo-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-2.jpg', 'filename'=>'arena-gatos-kikki-kat-carbon-activo-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-2.jpg'],
  ['producto_id'=>99, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-cleany-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-kikki-kat-cleany-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>99, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-cleany-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-1.jpg', 'filename'=>'arena-gatos-kikki-kat-cleany-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-1.jpg'],
  ['producto_id'=>99, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-cleany-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-2.jpg', 'filename'=>'arena-gatos-kikki-kat-cleany-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-2.jpg'],
  ['producto_id'=>100, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-lavanda-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-kikki-kat-lavanda-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>100, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-lavanda-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-1.jpg', 'filename'=>'arena-gatos-kikki-kat-lavanda-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-1.jpg'],
  ['producto_id'=>100, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-kikki-kat-lavanda-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-2.jpg', 'filename'=>'arena-gatos-kikki-kat-lavanda-4-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-2.jpg'],
  ['producto_id'=>101, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-stay-happy-cafe-moca-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'arena-gatos-stay-happy-cafe-moca-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>102, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-stay-happy-carbon-activo-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-stay-happy-carbon-activo-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>103, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-stay-happy-lavanda-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'arena-gatos-stay-happy-lavanda-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>104, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-zagret-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-zagret-10-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>105, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-raza-grande-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-perro-raza-grande-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>105, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-raza-grande-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'pro-plan-perro-raza-grande-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>105, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-raza-grande-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-2.webp', 'filename'=>'pro-plan-perro-raza-grande-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-2.webp'],
  ['producto_id'=>106, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-cachorro-raza-mediana-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'pro-plan-perro-cachorro-raza-mediana-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>106, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-cachorro-raza-mediana-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-perro-cachorro-raza-mediana-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>106, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-cachorro-raza-mediana-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-2.webp', 'filename'=>'pro-plan-perro-cachorro-raza-mediana-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-2.webp'],
  ['producto_id'=>107, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-raza-pequena-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-perro-raza-pequena-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>107, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-raza-pequena-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'pro-plan-perro-raza-pequena-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>107, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-raza-pequena-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-2.webp', 'filename'=>'pro-plan-perro-raza-pequena-adulto-7-kgs-mascotiendas-comida-perros-tienda-mascotas-la-serena-coquimbo-2.webp'],
  ['producto_id'=>108, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-funcion-renal-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-funcion-renal-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>108, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-funcion-renal-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-2.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-funcion-renal-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-2.webp'],
  ['producto_id'=>109, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-piel-sensible-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-piel-sensible-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>109, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-piel-sensible-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-piel-sensible-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>110, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-cardio-cuidado-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-cardio-cuidado-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>110, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-cardio-cuidado-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-cardio-cuidado-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>110, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-cardio-cuidado-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-2.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-cardio-cuidado-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-2.webp'],
  ['producto_id'=>111, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-movilidad-articular-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-2.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-movilidad-articular-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-2.webp'],
  ['producto_id'=>111, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-movilidad-articular-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1-1.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-movilidad-articular-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1-1.webp'],
  ['producto_id'=>112, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-ncuidado-neurologico-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-ncuidado-neurologico-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>112, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-ncuidado-neurologico-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-ncuidado-neurologico-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>113, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-tracto-problemas-urinarios-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-tracto-problemas-urinarios-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo.webp'],
  ['producto_id'=>113, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/pro-plan-perro-veterinary-dieta-tracto-problemas-urinarios-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp', 'filename'=>'pro-plan-perro-veterinary-dieta-tracto-problemas-urinarios-7-kgs-mascotiendas-cl-comida-para-perros-tienda-mascotas-la-serena-coquimbo-1.webp'],
  ['producto_id'=>114, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-sanicat-12-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-la-antena.jpg', 'filename'=>'arena-gatos-sanicat-12-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo-la-antena.jpg'],
  ['producto_id'=>115, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/arena-gatos-aegean-20-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg', 'filename'=>'arena-gatos-aegean-20-kgs-mascotiendas-cl-arena-sanitaria-tienda-mascotas-la-serena-coquimbo.jpg'],
  ['producto_id'=>116, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/compinches-comida-perro-mascotiendas-la-serena-coquimbo-tienda-mascotas-25-kgs.webp', 'filename'=>'compinches-comida-perro-mascotiendas-la-serena-coquimbo-tienda-mascotas-25-kgs.webp'],
  ['producto_id'=>117, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/odwalla-perro-adulto-25-kgs-mascotiendas-la-serena-la-antena-coquimbo-tienda-mascotas.jpg', 'filename'=>'odwalla-perro-adulto-25-kgs-mascotiendas-la-serena-la-antena-coquimbo-tienda-mascotas.jpg'],
  ['producto_id'=>118, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/purina-perro-cuidado-piel-skin-care-adulto-todas-razas-15-kgs-mascotiendas-la-serena-coquimbo-tienda-mascotas-la-antena.webp', 'filename'=>'purina-perro-cuidado-piel-skin-care-adulto-todas-razas-15-kgs-mascotiendas-la-serena-coquimbo-tienda-mascotas-la-antena.webp'],
  ['producto_id'=>119, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/purina-perro-purina-excellent-adulto-raza-mediana-grande-pollo-arroz-15-kgs-mascotiendas-la-serena-coquimbo-tienda-mascotas-la-antena.jpg', 'filename'=>'purina-perro-purina-excellent-adulto-raza-mediana-grande-pollo-arroz-15-kgs-mascotiendas-la-serena-coquimbo-tienda-mascotas-la-antena.jpg'],
  ['producto_id'=>119, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/purina-perro-purina-excellent-adulto-raza-mediana-grande-pollo-arroz-15-kgs-mascotiendas-la-serena-coquimbo-tienda-mascotas-la-antena-1.jpg', 'filename'=>'purina-perro-purina-excellent-adulto-raza-mediana-grande-pollo-arroz-15-kgs-mascotiendas-la-serena-coquimbo-tienda-mascotas-la-antena-1.jpg'],
  ['producto_id'=>120, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/purina-perro-purina-one-raza-pequena-mini-pollo-carne-mascotiendas-la-serena-coquimbo-tienda-mascotas-la-antena.jpg', 'filename'=>'purina-perro-purina-one-raza-pequena-mini-pollo-carne-mascotiendas-la-serena-coquimbo-tienda-mascotas-la-antena.jpg'],
  ['producto_id'=>121, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/vet-solution-urinary-struvite-gatos-problemas-urinarios-1-5-kgs-mascotiendas-la-serena-coquimbo-la-antena-tienda-mascotas-comida-gatos.jpg', 'filename'=>'vet-solution-urinary-struvite-gatos-problemas-urinarios-1-5-kgs-mascotiendas-la-serena-coquimbo-la-antena-tienda-mascotas-comida-gatos.jpg'],
  ['producto_id'=>122, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/vet-solution-renal-gatos-problemas-renales-1-5-kgs-mascotiendas-la-serena-coquimbo-la-antena-tienda-mascotas-comida-gatos.png', 'filename'=>'vet-solution-renal-gatos-problemas-renales-1-5-kgs-mascotiendas-la-serena-coquimbo-la-antena-tienda-mascotas-comida-gatos.png'],
  ['producto_id'=>123, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/08/bil-jac-comida-perro-picky-no-more-raza-pequena-mascotiendas-la-serena-la-antena-coquimbo-tienda-mascotas.png', 'filename'=>'bil-jac-comida-perro-picky-no-more-raza-pequena-mascotiendas-la-serena-la-antena-coquimbo-tienda-mascotas.png'],
  ['producto_id'=>124, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/09/forza-20-kgs-comida-perros-premium-la-serena-coquimbo-mascotiendas-tienda-mascotas-e1695613648139.webp', 'filename'=>'forza-20-kgs-comida-perros-premium-la-serena-coquimbo-mascotiendas-tienda-mascotas-e1695613648139.webp'],
  ['producto_id'=>124, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2023/09/forza-20-kgs-comida-perros-premium-la-serena-coquimbo-mascotiendas-tienda-mascotas-1-1.webp', 'filename'=>'forza-20-kgs-comida-perros-premium-la-serena-coquimbo-mascotiendas-tienda-mascotas-1-1.webp'],
  ['producto_id'=>125, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/pixelcut-export.jpeg', 'filename'=>'pixelcut-export.jpeg'],
  ['producto_id'=>125, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/pixelcut-export.jpeg', 'filename'=>'pixelcut-export.jpeg'],
  ['producto_id'=>126, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/pixelcut-export.jpeg', 'filename'=>'pixelcut-export.jpeg'],
  ['producto_id'=>127, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/spectra_7-5kg_1comp6335-2.jpg', 'filename'=>'spectra_7-5kg_1comp6335-2.jpg'],
  ['producto_id'=>128, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/spectra_7-5kg_1comp6335-2.jpg', 'filename'=>'spectra_7-5kg_1comp6335-2.jpg'],
  ['producto_id'=>129, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/NEXGARD-SPECTRA-15-A-30-KILOS.jpg', 'filename'=>'NEXGARD-SPECTRA-15-A-30-KILOS.jpg'],
  ['producto_id'=>130, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/NEXGARD-SPECTRA-15-A-30-KILOS.jpg', 'filename'=>'NEXGARD-SPECTRA-15-A-30-KILOS.jpg'],
  ['producto_id'=>131, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/nexgard-spectra-301-60-kg-900524.png.webp', 'filename'=>'nexgard-spectra-301-60-kg-900524.png.webp'],
  ['producto_id'=>132, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/nexgard-spectra-301-60-kg-900524.png.webp', 'filename'=>'nexgard-spectra-301-60-kg-900524.png.webp'],
  ['producto_id'=>133, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/pixelcut-export-2.jpeg', 'filename'=>'pixelcut-export-2.jpeg'],
  ['producto_id'=>134, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/credelio-22kg-45kg3577.jpg', 'filename'=>'credelio-22kg-45kg3577.jpg'],
  ['producto_id'=>135, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/leroy-173616.png', 'filename'=>'leroy-173616.png'],
  ['producto_id'=>136, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/credelio-22kg-45kg3577.jpg', 'filename'=>'credelio-22kg-45kg3577.jpg'],
  ['producto_id'=>137, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/5420036944126.webp', 'filename'=>'5420036944126.webp'],
  ['producto_id'=>138, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/credelio-25-55-kg-1125mg-3-comprimidos-811748.png.webp', 'filename'=>'credelio-25-55-kg-1125mg-3-comprimidos-811748.png.webp'],
  ['producto_id'=>139, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/5420036944126.webp', 'filename'=>'5420036944126.webp'],
  ['producto_id'=>140, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/credelio-25-55-kg-1125mg-3-comprimidos-811748.png.webp', 'filename'=>'credelio-25-55-kg-1125mg-3-comprimidos-811748.png.webp'],
  ['producto_id'=>141, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/credelio-450mg.png', 'filename'=>'credelio-450mg.png'],
  ['producto_id'=>142, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/credelio-450mg.png', 'filename'=>'credelio-450mg.png'],
  ['producto_id'=>143, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/5420036944140.webp', 'filename'=>'5420036944140.webp'],
  ['producto_id'=>144, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/5420036944140.webp', 'filename'=>'5420036944140.webp'],
  ['producto_id'=>145, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/PRODUCTOS-PAGINA-WEB.jpg', 'filename'=>'PRODUCTOS-PAGINA-WEB.jpg'],
  ['producto_id'=>146, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/CHICKENS-TENDERS.png', 'filename'=>'CHICKENS-TENDERS.png'],
  ['producto_id'=>147, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/TRAINING-TREATS.png', 'filename'=>'TRAINING-TREATS.png'],
  ['producto_id'=>148, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/MEAT-MEDALLIONS.jpg', 'filename'=>'MEAT-MEDALLIONS.jpg'],
  ['producto_id'=>149, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/TRAINING-TREATS-QUAIL.jpg', 'filename'=>'TRAINING-TREATS-QUAIL.jpg'],
  ['producto_id'=>150, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/DUCK-MEAT-STICK.jpg', 'filename'=>'DUCK-MEAT-STICK.jpg'],
  ['producto_id'=>151, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/LAMB-MEAT-STICKS.jpg', 'filename'=>'LAMB-MEAT-STICKS.jpg'],
  ['producto_id'=>152, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/LAMB-MEDALLIONS.jpg', 'filename'=>'LAMB-MEDALLIONS.jpg'],
  ['producto_id'=>153, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/MEAT-SLICES-VENISON.jpg', 'filename'=>'MEAT-SLICES-VENISON.jpg'],
  ['producto_id'=>154, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/PRODUCTOS-PAGINA-WEB-2.jpg', 'filename'=>'PRODUCTOS-PAGINA-WEB-2.jpg'],
  ['producto_id'=>155, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/TRAINING-TREATS-RABBIT.jpg', 'filename'=>'TRAINING-TREATS-RABBIT.jpg'],
  ['producto_id'=>156, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/08/TRAINING-TREATS-TURKEY.jpg', 'filename'=>'TRAINING-TREATS-TURKEY.jpg'],
  ['producto_id'=>157, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/TURKEY-SLICES.jpg', 'filename'=>'TURKEY-SLICES.jpg'],
  ['producto_id'=>158, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/DUCK-TENDERS.jpg', 'filename'=>'DUCK-TENDERS.jpg'],
  ['producto_id'=>159, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/MEAT-SLICES-GOOSE.jpg', 'filename'=>'MEAT-SLICES-GOOSE.jpg'],
  ['producto_id'=>160, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/JERKY-PROTEICO-VACUNO.jpg', 'filename'=>'JERKY-PROTEICO-VACUNO.jpg'],
  ['producto_id'=>161, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/JERKY-PROTEICO-SALMON.jpg', 'filename'=>'JERKY-PROTEICO-SALMON.jpg'],
  ['producto_id'=>162, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/JERKY-VACUNO.jpg', 'filename'=>'JERKY-VACUNO.jpg'],
  ['producto_id'=>163, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/JERKY-CORDERO.jpg', 'filename'=>'JERKY-CORDERO.jpg'],
  ['producto_id'=>164, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/JERKY-POLLO.jpg', 'filename'=>'JERKY-POLLO.jpg'],
  ['producto_id'=>165, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/JERKY-SALMON.jpg', 'filename'=>'JERKY-SALMON.jpg'],
  ['producto_id'=>166, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/SNACK-PREMIUM-OREJA-DE-CERDO.jpg', 'filename'=>'SNACK-PREMIUM-OREJA-DE-CERDO.jpg'],
  ['producto_id'=>167, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-SALMON.jpg', 'filename'=>'GALLETAS-GATOS-SALMON.jpg'],
  ['producto_id'=>168, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-ATUN-SALMON-1.jpg', 'filename'=>'GALLETAS-GATOS-ATUN-SALMON-1.jpg'],
  ['producto_id'=>169, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-CANGREJO.jpg', 'filename'=>'GALLETAS-GATOS-CANGREJO.jpg'],
  ['producto_id'=>170, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-CAMOTE-Y-CORDERO.jpg', 'filename'=>'GALLETAS-GATOS-CAMOTE-Y-CORDERO.jpg'],
  ['producto_id'=>171, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-CONEJO.jpg', 'filename'=>'GALLETAS-GATOS-CONEJO.jpg'],
  ['producto_id'=>172, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-COSTILLITAS-DE-CORDERO.jpg', 'filename'=>'GALLETAS-GATOS-COSTILLITAS-DE-CORDERO.jpg'],
  ['producto_id'=>173, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-DENTAL-MIX.jpg', 'filename'=>'GALLETAS-GATOS-DENTAL-MIX.jpg'],
  ['producto_id'=>174, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-ESPIRAL-DE-SALMON.jpg', 'filename'=>'GALLETAS-GATOS-ESPIRAL-DE-SALMON.jpg'],
  ['producto_id'=>175, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-SALCHICHA-DE-PATO.jpg', 'filename'=>'GALLETAS-GATOS-SALCHICHA-DE-PATO.jpg'],
  ['producto_id'=>176, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-TIRITAS-DE-POLLO.jpg', 'filename'=>'GALLETAS-GATOS-TIRITAS-DE-POLLO.jpg'],
  ['producto_id'=>177, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/GALLETAS-GATOS-TRUTRO-DE-POLLO.jpg', 'filename'=>'GALLETAS-GATOS-TRUTRO-DE-POLLO.jpg'],
  ['producto_id'=>178, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/FASHION-CAT-CAT-LITTER-NATURAL.jpg', 'filename'=>'FASHION-CAT-CAT-LITTER-NATURAL.jpg'],
  ['producto_id'=>179, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/FUNNY-BUNNY-500GR.jpg', 'filename'=>'FUNNY-BUNNY-500GR.jpg'],
  ['producto_id'=>180, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/FUNNY-BUNNY-1.8-KG.jpg', 'filename'=>'FUNNY-BUNNY-1.8-KG.jpg'],
  ['producto_id'=>181, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/JAZZ-CARNE-GATO-ADULTO.jpg', 'filename'=>'JAZZ-CARNE-GATO-ADULTO.jpg'],
  ['producto_id'=>182, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/BRAVERY-PERRO-ADULTO-CHICKEN.jpg', 'filename'=>'BRAVERY-PERRO-ADULTO-CHICKEN.jpg'],
  ['producto_id'=>183, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/BRAVERY-PERRO-ADULTO-IBERIAN-PORK.jpg', 'filename'=>'BRAVERY-PERRO-ADULTO-IBERIAN-PORK.jpg'],
  ['producto_id'=>184, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/BRAVERY-PERRO-ADULTO-LAMB.jpg', 'filename'=>'BRAVERY-PERRO-ADULTO-LAMB.jpg'],
  ['producto_id'=>185, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/BRAVERY-PERRO-PUPPY-CHICKEN.jpg', 'filename'=>'BRAVERY-PERRO-PUPPY-CHICKEN.jpg'],
  ['producto_id'=>186, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/BRAVERY-PERRO-PUPPY-SALMON.jpg', 'filename'=>'BRAVERY-PERRO-PUPPY-SALMON.jpg'],
  ['producto_id'=>187, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/MASTIN-PREMIUM-DOG-ADULTO.jpg', 'filename'=>'MASTIN-PREMIUM-DOG-ADULTO.jpg'],
  ['producto_id'=>188, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/VITALCAN-PREMIUM-CORDERO-ADULTO.jpg', 'filename'=>'VITALCAN-PREMIUM-CORDERO-ADULTO.jpg'],
  ['producto_id'=>189, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/CHURU-CREMA-PERRO-POLLO-Y-ATUN.jpg', 'filename'=>'CHURU-CREMA-PERRO-POLLO-Y-ATUN.jpg'],
  ['producto_id'=>189, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/CHURU-CREMA-PERRO-POLLO-Y-QUESO.jpg', 'filename'=>'CHURU-CREMA-PERRO-POLLO-Y-QUESO.jpg'],
  ['producto_id'=>189, 'posicion'=>2, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/CHURU-CREMA-PERRO-POLLO.jpg', 'filename'=>'CHURU-CREMA-PERRO-POLLO.jpg'],
  ['producto_id'=>189, 'posicion'=>3, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/CHURU-CREMA-PERRO-POLLO-Y-SALMON.jpg', 'filename'=>'CHURU-CREMA-PERRO-POLLO-Y-SALMON.jpg'],
  ['producto_id'=>190, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/ZUPET-POLLO-PARA-GATOS.jpg', 'filename'=>'ZUPET-POLLO-PARA-GATOS.jpg'],
  ['producto_id'=>190, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/ZUPET-BOVINO-PARA-GATOS.jpg', 'filename'=>'ZUPET-BOVINO-PARA-GATOS.jpg'],
  ['producto_id'=>191, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/DOGGO-ASTAS-DE-CIERVO-PARA-RAZAS-GRANDES.jpg', 'filename'=>'DOGGO-ASTAS-DE-CIERVO-PARA-RAZAS-GRANDES.jpg'],
  ['producto_id'=>192, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2024/09/DOGGO-ASTAS-DE-CIERVO-PARA-RAZAS-MEDIANAS.jpg', 'filename'=>'DOGGO-ASTAS-DE-CIERVO-PARA-RAZAS-MEDIANAS.jpg'],
  ['producto_id'=>193, 'posicion'=>0, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2025/04/WhatsApp-Image-2025-04-17-at-12.26.05-PM.jpeg', 'filename'=>'WhatsApp-Image-2025-04-17-at-12.26.05-PM.jpeg'],
  ['producto_id'=>193, 'posicion'=>1, 'url'=>'https://mascotiendas.cl/wp-content/uploads/2025/04/WhatsApp-Image-2025-04-17-at-12.26.05-PM.jpeg', 'filename'=>'WhatsApp-Image-2025-04-17-at-12.26.05-PM.jpeg']
];

// ─── DESCARGA ───────────────────────────────────
$ok = 0; $skip = 0; $error = 0;
echo "<hr><h3>Descargando imágenes...</h3><pre>";

foreach ($imagenes as $img) {
    $dest = IMG_DIR . $img['filename'];

    // Si ya existe, saltar
    if (file_exists($dest)) {
        echo "⏭  [SKIP] " . $img['filename'] . "\n";
        $skip++;

        // Igual actualizamos la URL en BD por si acaso
        $nuevaUrl = IMG_URL . $img['filename'];
        $stmt = $pdo->prepare(
            "UPDATE producto_imagenes SET url = ? WHERE producto_id = ? AND posicion = ?"
        );
        $stmt->execute([$nuevaUrl, $img['producto_id'], $img['posicion']]);
        continue;
    }

    // Descargar con file_get_contents (SiteGround lo permite)
    $ctx = stream_context_create(['http' => [
        'timeout'     => 20,
        'user_agent'  => 'Mozilla/5.0 (compatible; MascotiendaBot/1.0)',
        'ignore_errors' => true,
    ]]);

    $data = @file_get_contents($img['url'], false, $ctx);

    if ($data === false || strlen($data) < 1000) {
        echo "❌ [ERROR] " . $img['filename'] . " (no descargada)\n";
        $error++;
        continue;
    }

    file_put_contents($dest, $data);

    // Actualizar URL en BD
    $nuevaUrl = IMG_URL . $img['filename'];
    $stmt = $pdo->prepare(
        "UPDATE producto_imagenes SET url = ? WHERE producto_id = ? AND posicion = ?"
    );
    $stmt->execute([$nuevaUrl, $img['producto_id'], $img['posicion']]);

    echo "✅ [OK]    " . $img['filename'] . "\n";
    $ok++;

    // Pequeña pausa para no sobrecargar el servidor origen
    usleep(100000); // 0.1 segundos
}

echo "</pre><hr>";
echo "<h3>Resumen</h3>";
echo "<p>✅ Descargadas: <strong>$ok</strong></p>";
echo "<p>⏭  Saltadas (ya existían): <strong>$skip</strong></p>";
echo "<p>❌ Errores: <strong>$error</strong></p>";
echo "<p style='color:red;font-weight:bold'>⚠️ ELIMINA ESTE ARCHIVO del servidor ahora que terminó.</p>";
